export const dom = {
    email: document.getElementById("email"),
    password: document.getElementById("password"),
    loginArea: document.getElementById("loginArea"),
    loginBtn: document.getElementById("loginBtn"),
    passwordToggleBtn: document.getElementById("passwordToggleBtn"),
    keepLoginCheck: document.getElementById("keepLoginCheck"),
    appContent: document.getElementById("appContent"),

    welcomeBox: document.getElementById("welcomeBox"),
    welcomeName: document.getElementById("welcomeName"),

    topMenu: document.getElementById("topMenu"),
    menuBtn: document.getElementById("menuBtn"),
    menuDropdown: document.getElementById("menuDropdown"),
    openMainBtn: document.getElementById("openMainBtn"),
    openAdminBtn: document.getElementById("openAdminBtn"),
    menuLogoutBtn: document.getElementById("menuLogoutBtn"),

    mainScreen: document.getElementById("mainScreen"),
    adminScreen: document.getElementById("adminScreen"),
    adminMaintenanceBanner: document.getElementById("adminMaintenanceBanner"),
    maintenanceScreen: document.getElementById("maintenanceScreen"),
    maintenanceTitleView: document.getElementById("maintenanceTitleView"),
    maintenanceMessageView: document.getElementById("maintenanceMessageView"),
    maintenanceEndView: document.getElementById("maintenanceEndView"),
    maintenanceUpdatedByView: document.getElementById("maintenanceUpdatedByView"),
    maintenanceUpdatedAtView: document.getElementById("maintenanceUpdatedAtView"),

    mainTabButtons: document.querySelectorAll(".mainTabBtn"),
    mainTabPanels: document.querySelectorAll(".mainTabPanel"),
    mainTabHistory: document.getElementById("mainTabHistory"),
    mainTabManual: document.getElementById("mainTabManual"),
    mainTabHoliday: document.getElementById("mainTabHoliday"),
    mainTabReport: document.getElementById("mainTabReport"),

    adminTabButtons: document.querySelectorAll(".adminTabBtn"),
    adminTabPanels: document.querySelectorAll(".adminTabPanel"),
    adminTabDashboard: document.getElementById("adminTabDashboard"),
    adminTabNotice: document.getElementById("adminTabNotice"),
    adminTabEmployees: document.getElementById("adminTabEmployees"),
    adminTabHistory: document.getElementById("adminTabHistory"),
    adminTabManual: document.getElementById("adminTabManual"),
    adminTabHoliday: document.getElementById("adminTabHoliday"),
    adminTabReport: document.getElementById("adminTabReport"),
    adminTabMaintenance: document.getElementById("adminTabMaintenance"),

    clockInBtn: document.getElementById("clockInBtn"),
    clockOutBtn: document.getElementById("clockOutBtn"),
    currentWorkStatusCard: document.getElementById("currentWorkStatusCard"),

    noticeTitle: document.getElementById("noticeTitle"),
    noticeBody: document.getElementById("noticeBody"),
    addNoticeBtn: document.getElementById("addNoticeBtn"),
    noticeList: document.getElementById("noticeList"),
    adminNoticeList: document.getElementById("adminNoticeList"),

    employeeName: document.getElementById("employeeName"),
    employeeEmail: document.getElementById("employeeEmail"),
    employeeRole: document.getElementById("employeeRole"),
    addEmployeeBtn: document.getElementById("addEmployeeBtn"),
    employeeSelect: document.getElementById("employeeSelect"),
    employeeList: document.getElementById("employeeList"),
    newAccountName: document.getElementById("newAccountName"),
    newAccountEmail: document.getElementById("newAccountEmail"),
    newAccountPassword: document.getElementById("newAccountPassword"),
    newAccountRole: document.getElementById("newAccountRole"),
    createAccountBtn: document.getElementById("createAccountBtn"),
    checkAccountIntegrityBtn: document.getElementById("checkAccountIntegrityBtn"),
    accountIntegrityResult: document.getElementById("accountIntegrityResult"),
    roleChangeLogList: document.getElementById("roleChangeLogList"),

    myHistoryRangeType: document.getElementById("myHistoryRangeType"),
    myHistoryMonth: document.getElementById("myHistoryMonth"),
    myHistoryYear: document.getElementById("myHistoryYear"),
    mySummary: document.getElementById("mySummary"),

    manualWorkDate: document.getElementById("manualWorkDate"),
    manualClockInTime: document.getElementById("manualClockInTime"),
    manualClockOutTime: document.getElementById("manualClockOutTime"),
    manualAttendanceRows: document.getElementById("manualAttendanceRows"),
    addManualAttendanceRowBtn: document.getElementById("addManualAttendanceRowBtn"),
    addManualAttendanceBtn: document.getElementById("addManualAttendanceBtn"),

    myHolidayDate: document.getElementById("myHolidayDate"),
    myHolidayRows: document.getElementById("myHolidayRows"),
    addMyHolidayRowBtn: document.getElementById("addMyHolidayRowBtn"),
    addMyHolidayBtn: document.getElementById("addMyHolidayBtn"),

    history: document.getElementById("history"),
    prevPageBtn: document.getElementById("prevPageBtn"),
    nextPageBtn: document.getElementById("nextPageBtn"),

    adminDashboard: document.getElementById("adminDashboard"),
    todayEmployeeStatusList: document.getElementById("todayEmployeeStatusList"),

    adminHistoryEmployeeSelect: document.getElementById("adminHistoryEmployeeSelect"),
    adminHistoryRangeType: document.getElementById("adminHistoryRangeType"),
    adminHistoryMonth: document.getElementById("adminHistoryMonth"),
    adminHistoryYear: document.getElementById("adminHistoryYear"),
    adminSummary: document.getElementById("adminSummary"),
    adminWorkChart: document.getElementById("adminWorkChart"),
    adminChartPlaceholder: document.getElementById("adminChartPlaceholder"),
    adminHistory: document.getElementById("adminHistory"),
    adminPrevPageBtn: document.getElementById("adminPrevPageBtn"),
    adminNextPageBtn: document.getElementById("adminNextPageBtn"),

    adminManualEmployeeSelect: document.getElementById("adminManualEmployeeSelect"),
    adminManualWorkDate: document.getElementById("adminManualWorkDate"),
    adminManualClockInTime: document.getElementById("adminManualClockInTime"),
    adminManualClockOutTime: document.getElementById("adminManualClockOutTime"),
    adminManualAttendanceRows: document.getElementById("adminManualAttendanceRows"),
    addAdminManualAttendanceRowBtn: document.getElementById("addAdminManualAttendanceRowBtn"),
    adminAddManualAttendanceBtn: document.getElementById("adminAddManualAttendanceBtn"),

    adminHolidayEmployeeSelect: document.getElementById("adminHolidayEmployeeSelect"),
    adminHolidayDate: document.getElementById("adminHolidayDate"),
    adminHolidayRows: document.getElementById("adminHolidayRows"),
    addAdminHolidayRowBtn: document.getElementById("addAdminHolidayRowBtn"),
    addAdminHolidayBtn: document.getElementById("addAdminHolidayBtn"),

    downloadAdminPdfBtn: document.getElementById("downloadAdminPdfBtn"),
    monthlyReportPreview: document.getElementById("monthlyReportPreview"),
    deleteAllBtn: document.getElementById("deleteAllBtn"),

    maintenanceModeToggle: document.getElementById("maintenanceModeToggle"),
    maintenanceCurrentStatus: document.getElementById("maintenanceCurrentStatus"),
    maintenanceTitleInput: document.getElementById("maintenanceTitleInput"),
    maintenanceMessageInput: document.getElementById("maintenanceMessageInput"),
    maintenanceEndDatetimeRadio: document.getElementById("maintenanceEndDatetimeRadio"),
    maintenanceEndUnknownRadio: document.getElementById("maintenanceEndUnknownRadio"),
    maintenanceEndAtField: document.getElementById("maintenanceEndAtField"),
    maintenanceEndAtInput: document.getElementById("maintenanceEndAtInput"),
    maintenanceAdminUpdatedBy: document.getElementById("maintenanceAdminUpdatedBy"),
    maintenanceAdminUpdatedAt: document.getElementById("maintenanceAdminUpdatedAt"),
    saveMaintenanceBtn: document.getElementById("saveMaintenanceBtn")
}

